json.id category_painting.id
json.painting_id category_painting.painting_id
json.category_id category_painting.category_id
json.created_at category_painting.created_at
json.updated_at category_painting.updated_at
