# Category.create(name: "Original")
# Category.create(name: "Semi-Originals")
# Category.create(name: "Custom Commissioned Orders")
# Category.create(name: "Waterdale Collab Originals")

# User.create(name: "Yosefa", email: "yosefabruzoart@gmail.com", password: "yosefamakeup1", password_confirmation: "yosefamakeup1", admin: true)

# Painting.create(description: "Kever Rochel Purple")
# Painting.create(description: "Kosel")
# Painting.create(description: "Krias Yam Suf")
# Painting.create(description: "Kosel Green")
# Painting.create(description: "Painting Blue")
# Painting.create(description: "Kever Rochel")
# Painting.create(description: "Yerushalayim")
# Painting.create(description: "Kosel Light Blue")

# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711065939/arv19xacndfykmpivdvm.jpg", painting_id: 57)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711075141/xh4vxh4hmnlzti50tcss.jpg", painting_id: 58)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711075244/ykjpsxicmuu4kk0w1nvw.jpg", painting_id: 59)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711075512/ua3vwpiyywlau86olgxe.jpg", painting_id: 60)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711078088/zac7ecaobu9tlrgxrgfe.jpg", painting_id: 61)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711078172/t3xkjqtlpv102eze11rm.jpg", painting_id: 62)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711466770/f4e2cuacbnf6fydjzl4s.png", painting_id: 63)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711466836/iuoc0sbk0jvkr1g4b8cm.jpg", painting_id: 64)
