# Painting.create(image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWq-VofnQYns9YKDArJGbojQqKsbOwlmoPvfx8NqDIjg&s", description: "Sun rays on Kosel")

# Category.create(name: "Original")
# Category.create(name: "Semi-Originals")
# Category.create(name: "Custom Commissioned Orders")
# Category.create(name: "Waterdale Collab Originals")

# Image.create(url: "app/assets/images/kever-rochel.jpg", painting_id: 1)
# Image.create(url: "kever-rochel.jpg", painting_id: 1)
# Image.create(url: "https://i.pinimg.com/736x/cb/c6/62/cbc662299bd35357e519fe867444b86c.jpg", painting_id: 1)

# Painting.create(image: "71846e0d-e777-4aa8-9f38-a338a9414c68.jpeg", description: "Kosel Blue")
# Painting.create(image: "PHOTO-2024-03-03-16-46-47.jpg", description: "Blue People")
# Painting.create(image: "PHOTO-2024-03-03-16-46-47.jpg", description: " Bais Hamikdash and Yerushalayim")
# Painting.create(image: "PHOTO-2024-03-03-16-46-47.jpg", description: "Krias Yam Suf")
# Painting.create(image: "https://drive.google.com/file/d/1YyP7cwoUXknVR-4_FTVdlipLne4j2tid/view?ts=65dd374d", description: "Kever Rochel purple")
# Painting.create(image: "Kosel green 48x60 copy.jpg", description: "Kosel green")
# Painting.create(image: "https://drive.google.com/file/d/1avJv8qTJXSx-JfsGwy-MRQbjLObiUURM/view?ts=65dd374d", description: "Kosel")

# User.create(name: "Yosefa", email: "yosefabruzoart@gmail.com", password: "yosefamakeup1", password_confirmation: "yosefamakeup1", admin: true)

# Painting.create(description: "Kever Rochel Purple")
# Painting.create(description: "Kosel")
# Painting.create(description: "Krias Yam Suf")
# Painting.create(description: "Kosel Green")
# Painting.create(description: "Painting Blue")
# Painting.create(description: "Kever Rochel")
# Painting.create(description: "Yerushalayim")
# Painting.create(description: "Kosel Light Blue")

# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711065939/arv19xacndfykmpivdvm.jpg", painting_id: 34)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711075141/xh4vxh4hmnlzti50tcss.jpg", painting_id: 35)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711075244/ykjpsxicmuu4kk0w1nvw.jpg", painting_id: 36)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711075512/ua3vwpiyywlau86olgxe.jpg", painting_id: 39)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711078088/zac7ecaobu9tlrgxrgfe.jpg", painting_id: 40)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711078172/t3xkjqtlpv102eze11rm.jpg", painting_id: 41)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711466770/f4e2cuacbnf6fydjzl4s.png", painting_id: 53)
# Image.create(url: "https://res.cloudinary.com/dqbxtl2b9/image/upload/v1711466836/iuoc0sbk0jvkr1g4b8cm.jpg", painting_id: 54)
