# Painting.create(image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWq-VofnQYns9YKDArJGbojQqKsbOwlmoPvfx8NqDIjg&s", description: "Sun rays on Kosel")

# Category.create(name: "Original")
# Category.create(name: "Semi-Originals")
# Category.create(name: "Custom Commissioned Orders")
# Category.create(name: "Waterdale Collab Originals")
# Painting.create(image: "71846e0d-e777-4aa8-9f38-a338a9414c68.jpeg", description: "Kosel Blue")
# Painting.create(image: "PHOTO-2024-03-03-16-46-47.jpg", description: "Blue People")
# Painting.create(image: "PHOTO-2024-03-03-16-46-47.jpg", description: " Bais Hamikdash and Yerushalayim")
# Painting.create(image: "PHOTO-2024-03-03-16-46-47.jpg", description: "Krias Yam Suf")
# Painting.create(image: "https://drive.google.com/file/d/1YyP7cwoUXknVR-4_FTVdlipLne4j2tid/view?ts=65dd374d", description: "Kever Rochel purple")
# Painting.create(image: "Kosel green 48x60 copy.jpg", description: "Kosel green")
# Painting.create(image: "https://drive.google.com/file/d/1avJv8qTJXSx-JfsGwy-MRQbjLObiUURM/view?ts=65dd374d", description: "Kosel")
